[metadata]
name = rgbmatrix
version = 0.0.1
author = Christoph Friedrich
author_email = christoph.friedrich@vonaffenfels.de
maintainer = Chris Gill
maintainer_email = chris@chrisgill.net
description = Control RGB LED matrices with Raspberry Pi GPIO
long_description = file: README.md
long_description_content_type = text/markdown
license = GPL-2.0-or-later
url = https://github.com/hzeller/rpi-rgb-led-matrix
classifiers =
    Development Status :: 4 - Beta
    Intended Audience :: Developers
    Operating System :: POSIX :: Linux
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Cython
    Topic :: System :: Hardware

[options]
packages = rgbmatrix
package_dir =
    rgbmatrix = bindings/python/rgbmatrix
python_requires = >=3.8
zip_safe = False

[options.package_data]
rgbmatrix = *.pxd, *.pyx
